version: 2.1

jobs:
  build:

    working_directory: ~/Test_circleci

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: Test_circleci-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: Test_circleci-{{ checksum "pom.xml" }}

      - run: mvn package -DoutputDirectory=target
      - store_artifacts:
          path: target

      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
  WPT:
    docker:
      - image: webpagetest/agent
    steps:
      - run: echo "checking WPT image"
      - run:
          name: "run wpt"
          command: |
            docker images
            docker run webpagetest/agent
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - WPT