version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: maven build
          command: |
            mvn clean install