version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:latest-browsers
        user: root
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "wpt server"
          command: |
            docker run -d -p 4000:80 --rm webpagetest/server
      - run:
          name: "wpt agent"
          command: !
            docker run -d -p 4001:80 \
            --network="host" \
            -e "SERVER_URL=http://localhost:4000/work/" \
            -e "LOCATION=Test" \
            webpagetest/agent
